### ISSUE TITLE
IndexError調査

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#165]
```
[ERROR:2020-04-02 03:12:24,974] 'IndexError' object is not subscriptable
Traceback (most recent call last):
  File "/home/tsu-nera/repo/bakuchi_production/src/utils/trading.py", line 95, in run_trading
    arbitrage.run()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 64, in run
    self.next()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_base.py", line 24, in next
    x, y = self._get_tick()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 139, in _get_tick
    tick_x = Tick(x["timestamp"], x["bid"], x["ask"]) if x else None
TypeError: 'IndexError' object is not subscriptable

```

**Comment by tsu-nera** [comment]
```
            except IndexError:
                responses[thread] = None
            except Exception as e:
                traceback.format_exc(e)
                responses[thread] = e
```

とりあえずこれで対処。あとでもっと調べる。

**Comment by tsu-nera** [comment]
再現しないな..そもそもorder_bookだと取引が成立しない。

**Comment by tsu-nera** [comment]
order_bookはやめるのでいったん保留。issueは残しておく。

**Comment by tsu-nera** [comment]
order bookをやめても頻発していた。１日回せば10回くらい。調査。

```
Traceback (most recent call last):
 File "/home/tsu-nera/repo/bakuchi_production/src/utils/trading.py", line 95, in run_trading
   arbitrage.run()
 File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 64, in run
   self.next()
 File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_base.py", line 24, in next
   x, y = self._get_tick()
 File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 139, in _get_tick
   tick_x = Tick(x["timestamp"], x["bid"], x["ask"]) if x else None
TypeError: 'IndexError' object is not subscriptable
```

**Comment by tsu-nera** [comment]
threadingでtickを取得するのをやめたのでもうでないかな？
