### ISSUE TITLE
現状定義してあるinvokeコマンドを改めて全て動作させる

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#193]

**Comment by tsu-nera** [comment]
inv tick-ws-coincheckがクラッシュ

```
Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/tsu-nera/repo/bakuchi/tasks.py", line 114, in tick_ws_coincheck
    public.fetch_ws_ticks(ccxtconst.ExchangeId.COINCHECK)
  File "/home/tsu-nera/repo/bakuchi/src/utils/public.py", line 41, in fetch_ws_ticks
    client = WebsocketClient(exhange_id, symbol)
TypeError: __init__() missing 1 required positional argument: 'symbol'
```

**Comment by tsu-nera** [comment]
どうもやっぱり websocket系でクラッシュするな。そして、python-socketioはversionが以前は4だったが、5に更新されてる。この差分かな？

**Comment by tsu-nera** [comment]
v4だとうまく言った。サーバとの互換性の問題か？

**Comment by tsu-nera** [comment]
ついに、demoトレードが動いた。botのほうはslackへの通知でエラーしているな。

**Comment by tsu-nera** [comment]
よし、botが動いた。売買のapiでエラーしているが、そもそも仮想通貨を口座に入金していないからな。

**Comment by tsu-nera** [comment]
```
$ inv buy-coincheck

Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 594, in fetch
    response.raise_for_status()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://coincheck.com/api/exchange/orders

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/tsu-nera/repo/bakuchi/tasks.py", line 266, in buy_coincheck
    return buy_coincheck_with_amount(c, config.TRADE_AMOUNT)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/tsu-nera/repo/bakuchi/tasks.py", line 259, in buy_coincheck_with_amount
    float(amount))
  File "/home/tsu-nera/repo/bakuchi/src/utils/private.py", line 80, in create_coincheck_buy_order
    order_info = create_buy_order(exchange_id, symbol, amount, ask)
  File "/home/tsu-nera/repo/bakuchi/src/utils/private.py", line 44, in create_buy_order
    order_info = ex.order_buy(amount, ask_for_coincheck)
  File "/home/tsu-nera/repo/bakuchi/src/core/exchange_trading.py", line 58, in order_buy
    response = self.client.create_market_buy_order(price)
  File "/home/tsu-nera/repo/bakuchi/src/libs/ccxt_client.py", line 118, in create_market_buy_order
    amount=amount)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1888, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/coincheck.py", line 349, in create_order
    response = self.privatePostExchangeOrders(self.extend(request, params))
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 468, in inner
    return entry(_self, **inner_kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/coincheck.py", line 389, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 489, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 611, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 647, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: coincheck POST https://coincheck.com/api/exchange/orders 400 Bad Request {"success":false,"error":"Amount jpy の所持金額が足りません"}
```

**Comment by tsu-nera** [comment]
coincheckは一旦やめる予定なので、liquidのみ検証していく。

**Comment by tsu-nera** [comment]
おや、どういうことだ？liquidの最小取引単位は0.001ではなかったか？0.0005で取引が成立したぞ？

**Comment by tsu-nera** [comment]
おお、luquidは最小単位0.0001で取引できた。これは630円くらいにあたる。これなら小さく実験することができるのでよいな。coincheckは高すぎるぞ。

**Comment by tsu-nera** [comment]
よし、だいたいできたぞ。確認したらマージして closeする。
