### ISSUE TITLE
websocketのbitbank対応

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#202]
段階を踏まないとめんどくさそうなので、websocket対応は別対応とした。

**Comment by tsu-nera** [comment]
まずはboard-liquidとboard-bitbankを動作させる

**Comment by tsu-nera** [comment]
board-liquidは動いた

**Comment by tsu-nera** [comment]
board-bitbankはクラッシュ

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/bakuchi/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/miniconda3/envs/bakuchi/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/repo/bakuchi/src/libs/websocket_client.py", line 21, in fetch_ticks
    self.ws.fetch_ticks()
AttributeError: 'NoneType' object has no attribute 'fetch_ticks'

```

**Comment by tsu-nera** [comment]
bitbankのwebsocket仕様ドキュメント

https://github.com/bitbankinc/bitbank-api-docs/blob/master/public-stream_JP.md

**Comment by tsu-nera** [comment]
なにひとつwebsocketでデータがとれてなかった

**Comment by tsu-nera** [comment]
```
  File "/home/ubuntu/miniconda3/envs/bakuchi/lib/python3.7/site-packages/liquidtap/pysher/connection.py", line 107, in _connect
    self.socket = websocket.WebSocketApp(
AttributeError: module 'websocket' has no attribute 'WebSocketApp'
```

エラーするぞ？

**Comment by tsu-nera** [comment]
liquidtapは websocket-python v0.56で動いたが58では動かなかった

**Comment by tsu-nera** [comment]
謎のエラー

```
60002 成行買い注文の数量上限を上回っています

ccxt.base.errors.ExchangeError: bitbank {"success":"0","data":{"code":"60002"}}
```

**Comment by tsu-nera** [comment]
成功注文でなく指値が必要？
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q12196504377

**Comment by tsu-nera** [comment]
クラッシュは別issueに起こしたのでclose
