### ISSUE TITLE
generate-latest-reportがクラッシュしたので調べる

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#224]
```
⋊> ~/r/bakuchi on master ⨯ inv generate-latest-report         (bakuchi) 07:20:18
[NbConvertApp] Converting notebook reports/210403_0923/backtest.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python
[NbConvertApp] Writing 89429 bytes to reports/210403_0923/backtest.ipynb
[NbConvertApp] Converting notebook reports/210403_0923/backtest.ipynb to html
[NbConvertApp] Writing 659983 bytes to reports/210403_0923/backtest.html
[NbConvertApp] Converting notebook reports/210403_0923/trade.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python
Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/asyncio/tasks.py", line 219, in __step
    result = coro.send(None)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
profit_df = ta.create_profit_df()
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-cbed19a23fe1> in <module>
----> 1 profit_df = ta.create_profit_df()

~/repo/bakuchi/src/utils/trade_analysis.py in create_profit_df(self)
    201             'ex1_price': self.trades_ex1['price'].to_list(),
    202             'ex2_side': self.trades_ex2['side'].to_list(),
--> 203             'ex2_price': self.trades_ex2['price'].to_list()
    204         })
    205 

~/miniconda3/envs/bakuchi/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    527 
    528         elif isinstance(data, dict):
--> 529             mgr = init_dict(data, index, columns, dtype=dtype)
    530         elif isinstance(data, ma.MaskedArray):
    531             import numpy.ma.mrecords as mrecords

~/miniconda3/envs/bakuchi/lib/python3.7/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    285             arr if not is_datetime64tz_dtype(arr) else arr.copy() for arr in arrays
    286         ]
--> 287     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    288 
    289 

~/miniconda3/envs/bakuchi/lib/python3.7/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype, verify_integrity)
     78         # figure out the index, if necessary
     79         if index is None:
---> 80             index = extract_index(arrays)
     81         else:
     82             index = ensure_index(index)

~/miniconda3/envs/bakuchi/lib/python3.7/site-packages/pandas/core/internals/construction.py in extract_index(data)
    399             lengths = list(set(raw_lengths))
    400             if len(lengths) > 1:
--> 401                 raise ValueError("arrays must all be same length")
    402 
    403             if have_dicts:

ValueError: arrays must all be same length
ValueError: arrays must all be same length


```

**Comment by tsu-nera** [comment]
どうも、500レコード以上取得できていないぞ？

**Comment by tsu-nera** [comment]
あれ、500レコード以上って取得できないのか？

**Comment by tsu-nera** [comment]
500というのは決め打ちの値だったので、コードをいじって1000にしたら多くとることができた。ここをダイナミックに取得できるように改造する。

**Comment by tsu-nera** [comment]
#226
