### ISSUE TITLE
資金が少なくなったら自動停止させる

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#49]
dup: #71

**Comment by tsu-nera** [comment]
insufficientfundの例外が連続で発生したら停止？

**Comment by tsu-nera** [comment]
```
[ERROR:2020-03-25 01:38:20,368] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/tsu-nera/repo/bakuchi_production/src/utils/trading.py", line 83, in run_trading
    arbitrage.run()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 62, in run
    self.next()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_base.py", line 31, in next
    self._action(result, x, y)
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 216, in _action
    profit = self._calc_profit(buy_resp["jpy"], sell_resp["jpy"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tsu-nera** [comment]
```
Traceback (most recent call last):                                                                                              
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_parallel.py", line 27, in thread_worker                       
    responses[thread] = func_x()                                                                                                
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_parallel.py", line 66, in <lambda>                            
    ask_for_coincheck=ask)                                                                                                      
  File "/home/tsu-nera/repo/bakuchi_production/src/core/exchange_trading.py", line 53, in order_buy                             
    response = self.client.create_market_buy_order(price)                                                                       
  File "/home/tsu-nera/repo/bakuchi_production/src/libs/ccxt_client.py", line 114, in create_market_buy_order                   
    amount=amount)                                                                                                              
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1743, in create_market_b
uy_order                                                                                                                        
    return self.create_order(symbol, 'market', 'buy', amount, None, params)                                                     
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/coincheck.py", line 341, in create_order        
    response = self.privatePostExchangeOrders(self.extend(request, params))                                                     
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 441, in inner           
    return entry(_self, **inner_kwargs)                                                                                         
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/coincheck.py", line 381, in request             
    response = self.fetch2(path, api, method, params, headers, body)                                                            
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 460, in fetch2          
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])                                   
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 567, in fetch           
    self.handle_rest_errors(http_status_code, http_status_text, http_response, url, method)                                     
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 594, in handle_rest_erro
rs                                                                                                                              
    raise error(' '.join([method, url, string_code, http_status_text, body]))                                                   
ccxt.base.errors.ExchangeNotAvailable: POST https://coincheck.com/api/exchange/orders 400 Bad Request {"success":false,"error":"
Amount jpy の所持金額が足りません"} 
```

**Comment by tsu-nera** [comment]
```
    return self.fetch2(path, api, method, params, headers, body)                                                                                                                   [7/1985]
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 460, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 566, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/liquid.py", line 861, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, feedback)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 478, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InsufficientFunds: liquid {"errors":{"user":["not_enough_free_balance"]}}
```

**Comment by tsu-nera** [comment]
coincheckは `ExchangeNotAvailable`、liquidは`InsufficientFunds`になる。
