### ISSUE TITLE
運用中に liquid rate limitエラー発生

### ISSUE THREAD

**Issue by tsu-nera** [tsu-nera/bakuchi#68]
```
Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/bin/inv", line 8, in <module>
    sys.exit(program.run())
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/tsu-nera/repo/bakuchi_production/tasks.py", line 87, in trade
    run_trading()
  File "/home/tsu-nera/repo/bakuchi_production/src/utils/trading.py", line 21, in run_trading
    arbitrage.run()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 42, in run
    self.next()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_base.py", line 18, in next
    x, y = self._get_tick()
  File "/home/tsu-nera/repo/bakuchi_production/src/core/arbitrage_trading.py", line 48, in _get_tick
    return Tick(x["timestamp"], x["bid"],
TypeError: 'NoneType' object is not subscriptable
```

```
[ERROR]2020-03-14 01:49:49,659 liquid API rate limit exceeded. Please retry after 300s
Traceback (most recent call last):
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 554, in fetch
    response.raise_for_status()
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.liquid.com/products/5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsu-nera/repo/bakuchi_production/src/libs/ccxt_client.py", line 43, in _exec
    return self.exchange.fetch_ticker(self.symbol)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/liquid.py", line 378, in fetch_ticker
    response = self.publicGetProductsId(self.extend(request, params))
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 441, in inner
    return entry(_self, **inner_kwargs)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 464, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 460, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/base/exchange.py", line 566, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/home/tsu-nera/miniconda3/envs/bakuchi/lib/python3.7/site-packages/ccxt/liquid.py", line 838, in handle_errors
    raise DDoSProtection(self.id + ' ' + body)
ccxt.base.errors.DDoSProtection: liquid API rate limit exceeded. Please retry after 300s
[ERROR]2020-03-14 01:49:49,662 error occourd
[ERROR]2020-03-14 01:49:49,662 (liquid) can't get tick
```

**Comment by tsu-nera** [comment]
```
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.liquid.com/products/5
```

**Comment by tsu-nera** [comment]
いちおう、クラッシュしないような対策はいれておいた。
